name: Deploy
on:
  push:
    branches: 
    - master
    - rewrite
    paths-ignore:
    - '**.md'
    - '**.yml'
jobs:
  Test:
    name: Test Deployability
    runs-on: debian-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Deps
        run: npm install
      - name: Building
      run: |
        npm install
        nuxt generate --fail-on-error