name: Deploy
on:
  push:
    branches: 
      - master
      - rewrite
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  Test:
    name: Test Deployability
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14 
      - name: Install Deps
        run: |
         npm install
         npm install nuxt
      - name: Build
        run: |
          nuxt generate --fail-on-error
